### ISSUE TITLE
UART detection code is not robust enough

### ISSUE THREAD

**Issue by skiselev** [640-KB/GLaBIOS#28]
The UART detection code seems to rely on the fact that the UART will have bits 7-3 in the IIR reset to 0.
This is probably true for 8250 and 16450 UARTs. The 16550, 16550A, 16750, and various other newer UARTs can have non-zero values in bits 7-6 and 3.
Particularly, I observed an issue were GLaBIOS will not detect the UART after enabling FIFO on a 16550A UART and then warm-resetting the system (the SYSCHK utility mentioned here does that: https://github.com/skiselev/8088_bios/issues/31)

8088 BIOS uses a slightly more complicated approach: It writes 00001111b to IER, reads IER back, and verifies that it still has the same value, and then it writes 0 or IER, and again verifies that it reads back the same value

**Comment by 640-KB** [comment]
You are absolutely right - I did write it specifically with the 8250/16450 in mind and at the time wasn't considering any more advanced UARTs would be used on a PC - remember I set off to create a "pure" XT clone BIOS. :) 

Thanks for the heads up on that - I'll check it out.

**Comment by 640-KB** [comment]
I did a bit of research and came up with a few things that should alleviate this case.  Interestingly, I was able to reproduce the same thing on an AMI 386 BIOS from 1992, so apparently the `11111000b` "gold standard" port detect test stretched all the way into the 90's!  I've actually owned this actual 386 PC with a 16550A card since the 90's and can't recall ever running into this issue.

Anyway, as an improvement here's what I did: https://github.com/640-KB/GLaBIOS/commit/c9dd39d8b7b53a35fb190c7cdb7f52a328ee6687

1. In the port detection, it will first clear the FIFO Control Register (FCR) and disable FIFO
2. It reads the IIR twice which clears the DMA flags and a few other things
3. It only no longer checks bit 3 in the IIR. Apparently, that could be reset by reading RHR but couldn't see that the need justified the extra code bytes to do it.

As with the other, more testing is needed before calling this a stable change, but I think it splits the difference between solving the observable problem without any major changes to how it works.  What do you think?

Really appreciate your look and advice on this!

640KB

**Comment by skiselev** [comment]
That looks good to me. I can test it on my system when time allows (and maybe port it back to the 8088 BIOS hehe)

As far as 16550A go, I think in PC world they were introduced in IBM PS/2 Model 50 and up (not in the entry level models 25 and 30... but maybe they were used in 30/286?). And in the clones they've appeared a bit later, with 486 machines or so. Actually, the computers rarely contained 16550A UART itself, instead, the functionality was implemented as a part of Multi I/O controller. Some people who cared about UART performance used old school ISA cards that initially were designed for 8250 or 16450 and swapped that for 16550A. So it is not surprising that 386 BIOS doesn't care for a corner case in the 16550 detection

**Comment by 640-KB** [comment]
Cool. If you build from source, make sure to set the `MICRO_8088` option to `1` (in addition to `ARCH_TYPE EQU ARCH_FE2010`).  This is the only sub-type of an architecture build, so I need to make that a bit more elegant down the road but for now just do that. Otherwise, here is my [personal sandbox version](https://github.com/640-KB/GLaBIOS/releases/download/v0.2.3/GLABIOS_0.2.3_VF-M88_0.9.9_MFXTIDE_V20.bin) with GLaBIOS on the first and 8088 BIOS 0.9.9 on the second.  This also contains the [yet-to-be-released RTC option ROM](https://github.com/640-KB/GLaTICK) which adds support for the DS12885 INT 1Ah clock. This ROM was planned to support mostly legacy I/O clock cards, but since I have the board now I added this chip too.

Totally makes sense why the 16550A wouldn't be considered in the 386 generation of BIOSes.  That machine ran a BBS for years back in the day, so I had added that I/O card with the 16550A for that reason.  Good times.

640KB

**Comment by 640-KB** [comment]
Also @skiselev for what it's worth, I haven't been able to reproduce the issue with SysCheck on either version of 8088_bios or GLaBIOS on my NuXT board with V20.  I couldn't find a copy of SysCheck 2.45, so I'm using SysCheck 2.43... who knows if that makes any difference.  Also my board has the FE2010A and the OP mentioned having the PT8010AF, is the other difference.

**Comment by skiselev** [comment]
It could be a difference between FE2010A and PT8010AF as far as floating IRQ lines go (maybe FE2010A has built-in pull-downs?) I have to test it with FE2010A...
I put a pretty long description of my findings in https://github.com/skiselev/8088_bios/issues/31, but it boils down to the PIC generating lots of interrupts when IRQ lines are floating and respective interrupts are not masked
