### ISSUE TITLE
Turbo button not working on Juko ST

### ISSUE THREAD

**Issue by charlysan** [640-KB/GLaBIOS#35]
## Description

1 - PC always boots on Turbo Mode
2 - Pressing the Turbo Button does not trigger switch between Turbo and Normal mode.

`#1`: I guess this is related to `TURBO_TYPE` default value. 
`#2`: is this implemented? 

### Hardware

- Juko ST clone + NECv20 @ 12 MHz

### BIOS Version

[GLABIOS_0.2.4_VS.ROM](https://github.com/640-KB/GLaBIOS/releases/download/v0.2.4/GLABIOS_0.2.4_VS.ROM)

**Comment by 640-KB** [comment]
Some ST boards have hardware jumpers that override the software switch. As in, when it's closed the the hot keys have no effect. Maybe try removing that and see if that does the trick?

**Comment by charlysan** [comment]
The hot keys do work (ctrl, alt, +), what it doesn't work is the turbo switch (CN8).

**Comment by 640-KB** [comment]
Ah, got it - I misunderstood.  So this is different than the BIOS you were previously using?  Which one were you running before?

In the meantime, I'll set up my ST-12 and try it also.

**Comment by charlysan** [comment]
[This](https://github.com/charlysan/x86_stuff/blob/main/bios/roms/juko_baby_xt_bxm_12.bin) is the BIOS that originally came with the board, which is a slightly modified version of `v2.20`. This works as expected: `CN8 closed` => `Turbo Mode ON`; `CN8 open` => `Turbo Mode Off`

**Comment by 640-KB** [comment]
I booted this up on my ST-12 and I do see the same thing you do, where the hardware switch is always overridden by software (hot keys).  So again going without a data sheet or reasonable documentation we've got to just do this experimentally.  

In terms of the mechanics of how the hardware handles this, there are a few variables in play:

1. State of the Turbo button
2. State of Turbo/Normal speed
3. Does the switch function?

**There's a few ways I could see this work:**

1. Software only: hardware button is ignored.
2. When switch OFF, always LOW. When switch ON, controlled by software. Boots to high speed.
3. Software and hardware always toggle each other (hardware switch's ON/OFF position does not necessarily determine speed) ** this does not seem to be possible with this hardware

I created a table of all possible permutations of these states and came up with the following.  "Write" is the value written to register `90h`.  While the current speed can be read from `90h`, it is not possible to read the state of the hardware switch.

![image](https://user-images.githubusercontent.com/23486433/233879646-3787815c-b110-4dd4-8a8a-d11c62254445.png)

To achieve option #3, both "switch works" and "speed changed" columns would need to be true at the same time, for the **same** values of "write" (since you cannot know the state of the hardware button).  As there is no such permutation, it does not seem that this is possible on this motherboard.

Looking at the results, you can see that when the HW switch is ON, there are two possible states that will result in the speed changing and switch working going from LOW to HIGH, however, there are no permutations that would seem to have both the switch and the speed change going from HIGH to LOW.

Thinking back, I believe that we just left it working the way it does (software only) just because there wasn't enough real data for how it works.  Even with this chart, it's still not completely clear the best option for how it should work.

I did try your modified BIOS and if I recall, you need to install a TSR or use an external program to switch the speed with software which I don't have handy, so I really couldn't compare it exactly.

I'm out of time this evening to work on this any further, but if you have any thoughts or suggestions or can confirm any of these same findings independently or with the original BIOS please share them.

I would definitely would like to get this mystery solved so we can get identify the right way (or ways) for this to work going forward.

Thanks for bringing this up!

640KB

**Comment by 640-KB** [comment]
I tried the original ST-12 BIOS and the `TURBO.COM` software that comes with it and this is what it seems to do.

At boot the hardware switch controls the speed -- there is no software/keyboard control without the `TURBO.COM` TSR loaded.  Once loaded it appears to allow a choice between using the hardware switch or keyboard switching, but never both at the same time.  When `TURBO.COM` is loaded, there are three keyboard controls:
  - `Ctrl`-`alt`-`+` : Speed is TURBO / hardware switch is disabled
  - `Ctrl`-`alt`-`-` : Speed is LOW / hardware switch is disabled
  - `Ctrl`-`alt`-`*` : Speed is returned to hardware switch control

Currently, GLaBIOS doesn't support three keyboard-controlled speeds (though it has been suggested in #25) as this would require some refactoring and there currently isn't available code space to do that.

Based on that here are three ways I can imagine it could work:

1. Use a build-time option that determines the behavior - either under software or hardware control completely.  
2. The system boot to hardware switch control, where using a keyboard shortcut key disables the hardware switch.  This is more consistent with how the ST-12 BIOS works, only it won't have the `*` hotkey to return to hardware control.  Being that it would be restored to hardware control with a reboot (warm or cold) I doubt that would be a big deal.
3. Hardware control is enabled, and software control is enabled when hardware button is in ON (pressed).  If hardware button is OFF, speed will always be LOW regardless of keyboard switching.

My preference is #3 because it seems most intuitive and also shouldn't alter the behavior for existing ST-12 users, unless they do not have a hardware switch installed and have been using it in hardware "LOW" mode all this time.

Thoughts or suggestions?

640KB

**Comment by charlysan** [comment]
I like option `#3` too. As you said, it's the most intuitive. I'll try confirm your findings this week.

**Comment by 640-KB** [comment]
> I like option `#3` too. As you said, it's the most intuitive. I'll try confirm your findings this week.

Sounds good.  I'm going to add a hardware switch build option to enable hardware switch as described in #3 and make it the default.  If the prior behavior is desired it can be rebuilt with that flag off.  

In the meantime, if you want to try it here is a test build with that new option enabled:

https://github.com/640-KB/GLaBIOS/releases/download/v0.2.4/GLABIOS_0.2.4_VS_ST1.ROM

**Comment by 640-KB** [comment]
> I like option `#3` too. As you said, it's the most intuitive. I'll try confirm your findings this week.

Hi @charlysan.  Wondering if you had a chance to give this a test to see if it works better for you?  Just want to know if we can close this issue or not.

Thanks again for bringing this up!

**Comment by charlysan** [comment]
@640-KB, [this build](https://github.com/640-KB/GLaBIOS/releases/download/v0.2.4/GLABIOS_0.2.4_VS_ST1.ROM) fails to boot in my board. I get multiple beeping errors.

**Comment by 640-KB** [comment]
> @640-KB, [this build](https://github.com/640-KB/GLaBIOS/releases/download/v0.2.4/GLABIOS_0.2.4_VS_ST1.ROM) fails to boot in my board. I get multiple beeping errors. Does it work with yours?

@charlysan yes, I just re-flashed from this link and it works fine - it's actually the same as I have in my ST-12 computer already.

Do you know what the beeps are?  How many short and how many long?  Did the previous VS build work but not this one?  You have a V20 installed right (that image won't run on an 8088)?

**Comment by charlysan** [comment]
Beeping patter was quite indistinguishable. Hardware used is listed at the top of this thread. [Previous VS build](https://github.com/640-KB/GLaBIOS/releases/download/v0.2.4/GLABIOS_0.2.4_VS.ROM) works OK. I will try again today and share more details.

**Comment by charlysan** [comment]
@640-KB, I tried with different EPROM and it worked as expected. The issue I had was not related to GLABIOS.
Turbo button and software port 0x90 working as expected.

**Comment by 640-KB** [comment]
> @640-KB, I tried with different EPROM and it worked as expected. The issue I had was not related to GLABIOS. Turbo button and software port 0x90 working as expected.

Great!  Yes, I think this behavior is much better.  Thanks again for bringing this up and the suggestion!
