### ISSUE TITLE
How do I build this on Linux?

### ISSUE THREAD

**Issue by leapofazzam123** [640-KB/GLaBIOS#6]
MASM isn't available on Linux. I don't want to use Windows or DOSBox. Is there a MASM-like assembler that's available for Linux? Maybe convert it into a NASM-compatible syntax as a separate assembly file?

**Comment by 640-KB** [comment]
Hey there.  I'm not really very experienced in NASM and its toolsets so I just took the easy way out and used what I know.  That said I suppose there's a few ways to do it:

1. Could try to build it online using something like PCJS: (https://www.pcjs.org/software/pcx86/lang/microsoft/masm/5.00/).  It's a little cumbersome because you need to put the source onto a disk image and upload it, but I did try it and was able to do it just fine there, so it can be done with no software installed on your computer.
2. MASM 6.1 (maybe others) did come with a Win32 version so that could potentially be run under Wine or something similar.  Now I do know that (currently) the project doesn't build properly on MASM 6.x, which has been on my list to go back to and see if I can make it work on that version as well.
3. Emulators such as 86Box and PCem run on Linux nicely.  You'll probably need one of these anyway to test the BIOS?
4. I know you said you didn't want to use DOSBox, though that's how I did probably 98% of the development of this and it makes to so easy because the DOS VM and your host computer share a live file system so you just work inside the IDE/editor of your choice and MASM sees it live.
5. Someone far more skilled with NASM than I can create a fork of it and port it over.  I know NASM optionally allows a lot of MASM-like syntax so perhaps it might not be too bad if you know NASM well?

Thanks for checking it out - and let me know if you have any questions, comments or whatever.  Hopefully one of these (or a different one) will work for you.

**Comment by 640-KB** [comment]
Hey there.  I'm not really very experienced in NASM and its toolsets so I just took the easy way out and used what I know.  That said I suppose there's a few ways to do it:

1. Could try to build it online using something like PCJS: (https://www.pcjs.org/software/pcx86/lang/microsoft/masm/5.00/).  It's a little cumbersome because you need to put the source onto a disk image and upload it, but I did try it and was able to do it just fine there, so it can be done with no software installed on your computer.
2. MASM 6.1 (maybe others) did come with a Win32 version so that could potentially be run under Wine or something similar.  Now I do know that (currently) the project doesn't build properly on MASM 6.x, which has been on my list to go back to and see if I can make it work on that version as well.
3. Emulators such as 86Box and PCem run on Linux nicely.  You'll probably need one of these anyway to test the BIOS?
4. I know you said you didn't want to use DOSBox, though that's how I did probably 98% of the development of this and it makes to so easy because the DOS VM and your host computer share a live file system so you just work inside the IDE/editor of your choice and MASM sees it live.
5. Someone far more skilled with NASM than I can create a fork of it and port it over.  I know NASM optionally allows a lot of MASM-like syntax so perhaps it might not be too bad if you know NASM well?

Thanks for checking it out - and let me know if you have any questions, comments or whatever.  Hopefully one of these (or a different one) will work for you.

**Comment by 640-KB** [comment]
Hey there.  I'm not really very experienced in NASM and its toolsets so I just took the easy way out and used what I know.  That said I suppose there's a few ways to do it:

1. Could try to build it online using something like PCJS: (https://www.pcjs.org/software/pcx86/lang/microsoft/masm/5.00/).  It's a little cumbersome because you need to put the source onto a disk image and upload it, but I did try it and was able to do it just fine there, so it can be done with no software installed on your computer.
2. MASM 6.1 (maybe others) did come with a Win32 version so that could potentially be run under Wine or something similar.  Now I do know that (currently) the project doesn't build properly on MASM 6.x, which has been on my list to go back to and see if I can make it work on that version as well.
3. Emulators such as 86Box and PCem run on Linux nicely.  You'll probably need one of these anyway to test the BIOS?
4. I know you said you didn't want to use DOSBox, though that's how I did probably 98% of the development of this and it makes to so easy because the DOS VM and your host computer share a live file system so you just work inside the IDE/editor of your choice and MASM sees it live.
5. Someone far more skilled with NASM than I can create a fork of it and port it over.  I know NASM optionally allows a lot of MASM-like syntax so perhaps it might not be too bad if you know NASM well?

Thanks for checking it out - and let me know if you have any questions, comments or whatever.  Hopefully one of these (or a different one) will work for you.

**Comment by 640-KB** [comment]
FYI, the latest commit includes some fixes so it will build now on MASM 6.1.  Caveat - I don't plan to include MASM 6.1 in routine testing, so something might break in the future.  In which case let me know.

**Comment by ecm-pushbx** [comment]
You can check Japheth's JWASM, a fork of OpenWatcom's WASM that increases accuracy to MASM. (This is "open source" according to OSI but I think not DFSG/FSF "free software".) It runs natively under Linux too.

**Comment by 640-KB** [comment]
> You can check Japheth's JWASM, a fork of OpenWatcom's WASM that increases accuracy to MASM. (This is "open source" according to OSI but I think not DFSG/FSF "free software".) It runs natively under Linux too.

Great info - thanks!  I'll check it out sometime.
